### ISSUE TITLE
Nested struct

### ISSUE THREAD

**Issue by xoac** [softprops/envy#15]
```
#[derive(Deserialize, Debug)]
struct A {
  u: i32,
  y: String,
}
#[derive(Deserialize, Debug)]
struct B {
 a: A,
}
```

Is possible to de-serialize above? I would expected to work this as `A_U=5` `A_Y="Test"` or `A=U=5,y=Test` but it don't.

**Comment by softprops** [comment]
This is interesting but potentially might actually call for storing this configuration in medium that supports representing more complex structures like yaml/json/ect. 

envy if focused a more on flat key => value ( env style ) configuration. it seems like you may be wanting keya => keyb => keyc => value. Which is totally fine but not typically the kind format that envy is focused on. 

That said, I would be open to a pr for this if you're up for it if you have an idea of what you'd be looking for.

**Comment by xoac** [comment]
What I want it can be easy done with `#serde(flatten)`. So you can close issue if u dont want support nested structures ;)

**Comment by softprops** [comment]
I'm happy to take prs but it seems you've found a pathway. Thanks for reaching out. I'll take a look at the flatten attr

**Comment by softprops** [comment]
Dropping a note here for now for future folks that fall apon this issue https://serde.rs/attr-flatten.html
