### ISSUE TITLE
Adding a way to specify default values

### ISSUE THREAD

**Issue by hgrecco** [softprops/envy#2]
Many times environmental variables are optional for my applications. It would be nice to be able to specify some defaults.

**Comment by softprops** [comment]
That's a neat idea. I think serde may have a way to declare a default fallback with a field annotation. I'll do some digging and see what I can find.

**Comment by softprops** [comment]
It turns out serde does support this out of the box. I needed to make a few changes to ensure they were being honored so if you update to `0.1.1` you should be able to follow the example in the updated [usage](https://github.com/softprops/envy#usage) docs to learn how to declare default values

**Comment by hgrecco** [comment]
Nice!
