### ISSUE TITLE
Inconsistent results when running multiple unit tests that use envy

### ISSUE THREAD

**Issue by Spanfile** [softprops/envy#49]
## 🐛 Bug description
I am testing constructing a struct from different sets of environment variables using serde and envy. Each test begins by clearing the environment variables with `std::env::remove_var()` and then setting new values with `std::env::set_var()`. After the values are set, I print the currently set values with `std::env::vars()`, which are displayed correctly. After that, I construct the struct with envy, print what values it has and finally `assert_eq!` that they're correct. Using just a single test to test a certain set of values, it works every time, but using multiple tests to test different sets of environment variables causes the tests to fail randomly. This is because the values envy sets into the struct are *not* the ones the test just set, but the ones the previous test did. Since the order the tests are ran with `cargo test` isn't determenistic, the tests fail randomly.

#### 🤔 Expected Behavior
envy gets the proper environment variables and sets them accordingly in all tests.

#### 👟 Steps to reproduce
```rust
use serde::Deserialize;

const PREFIX: &str = "TEST_";

#[derive(Debug, Deserialize)]
struct Config {
    pub value_1: String,
    pub value_2: String,
}

impl Config {
    fn from_env() -> Config {
        envy::prefixed(PREFIX).from_env::<Config>().unwrap()
    }
}

fn dump_env_lines(prefix: &str) -> Vec<String> {
    std::env::vars()
        .filter_map(|(k, v)| {
            if k.starts_with(prefix) {
                Some(format!("{}={}", k, v))
            } else {
                None
            }
        })
        .collect::<Vec<String>>()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn test_1() {
        env::remove_var("TEST_VALUE_1");
        env::remove_var("TEST_VALUE_2");

        env::set_var("TEST_VALUE_1", "Hello");
        env::set_var("TEST_VALUE_2", "World");

        println!("{:?}", dump_env_lines(PREFIX));
        let config = Config::from_env();
        println!("{:?}", config);

        assert_eq!(config.value_1, "Hello");
        assert_eq!(config.value_2, "World");
    }

    #[test]
    fn test_2() {
        env::remove_var("TEST_VALUE_1");
        env::remove_var("TEST_VALUE_2");

        env::set_var("TEST_VALUE_1", "Test");
        env::set_var("TEST_VALUE_2", "Value");

        println!("{:?}", dump_env_lines(PREFIX));
        let config = Config::from_env();
        println!("{:?}", config);

        assert_eq!(config.value_1, "Test");
        assert_eq!(config.value_2, "Value");
    }
}
```

Example output of one failed test run:
```
---- tests::test_2 stdout ----
["TEST_VALUE_1=Test", "TEST_VALUE_2=Value"]
Config { value_1: "Hello", value_2: "World" }
thread 'tests::test_2' panicked at 'assertion failed: `(left == right)`
  left: `"Hello"`,
 right: `"Test"`', src/lib.rs:62:9
```
The output shows that the Config struct has the values `Hello` and `World`, which are the ones set in the previously ran test, instead of the values `Test` and `Value` the current test previously set.

#### 🌍 Your environment
* OS: Ubuntu 20.04
* `rustc 1.45.0 (5c1f21c3b 2020-07-13)` (latest stable at the time of writing)
* `cargo 1.45.0 (744bd1fbb 2020-06-15)`
* envy version: 0.4.1
* serde version: 1.0.114

**Comment by softprops** [comment]
@Spanfile env var storage is essentially shared mutable state. Rudy's test framework runs tests in parallel by default. When you mix the two this is expected behavior.

You have two options

1) unparallelize tests with `cargo test -- --test-threads=1`

2) use `from_iter` to test. You can find an example [here](https://github.com/softprops/envy/blob/eb2e88c294a06e86136aeff6dcb1fe56416614e5/src/lib.rs#L412)
