### ISSUE TITLE
deserializing enums - idea

### ISSUE THREAD

**Issue by SamuelMarks** [softprops/envy#5]
FYI: should be easy enough to implement with https://doc.rust-lang.org/std/path/

**Comment by softprops** [comment]
enums are a neat idea and may actually be a more straight forward thing to do with the latest version of serde, which Im trying to upgrade to right now. ill look into that after I get this next release out. It seems their api has changed quiet a bit with 0.9 but it seems in a good way.

**Comment by softprops** [comment]
This got easier with the latest serde. I just released [0.3.0](https://crates.io/crates/envy) which upgrades our dependency on serde to 1.0. I added enum support to the tests. You can find an example using enums [here](https://github.com/softprops/envy/blob/master/serde-tests/test.rs#L6-L37)
