### ISSUE TITLE
Map deserialization syntax?

### ISSUE THREAD

**Issue by hutchisr** [softprops/envy#56]
I can't find any documentation on how to pass map fields to be deserialized.

For example, given
```rust
use std::collections::HashMap;
use serde_derive::Deserialize;

#[derive(Debug, Default, Deserialize)]
struct Config {
    services: HashMap<String, String>
}

envy::from_env::<Config>()
```

How does one actually pass values to `services`?

I've tried `SERVICES=a=test,b=test`, which results in `Err(Custom("invalid type: string \"a=test,b=test\", expected a map"))` and `SERVICES_A=test` which causes `Err(MissingValue("services"))`

Is there a way to do this?

envy version: 0.4.2

**Comment by softprops** [comment]
This is not currently supported as there is no standard way to convey nested structures with environment variables.  Environment variables are inherently a flat set of keys and values

 I design mistake I think I made early on is assuming a convention for vec's for values, a comma separated string. I'm open to suggestions based on common conventions used elsewhere but I have not bumped into any that are commonly adopted.

Aside: envy target use case is for typed configuration. In your case are the service names well known?

If so another way to structure this would be 

```rust
#[derive(Debug, Default, Deserialize)]
struct Services {
    a: String,
    b: String
}

let Services { a, b } = envy::from_env::<Services>()?;
```

You could also leverage the existing support for `Vec` and choice a format you decide.

```rust
#[derive(Debug, Default, Deserialize)]
struct Config {
    services: Vec<String>
}

let services = envy::from_env::<Config>().services
    .into_iter()
    .fold(HashMap::new(), move |mut result, svc| {
        // scheme is based on your example above
        match svc.split('=').collect::<Vec<_>>()[..] {
            [name, value] => {
                result.insert(name.to_owned(), value.to_owned());
            }
            _ => {
                panic!("invalid service {}", svc);
            }
        }
        result
    });
```

**Comment by hutchisr** [comment]
Yeah, I'm not sure what a universal convention would be for this, so it does make sense it's not included in retrospect. 

For anyone with a similar use case, I did end up finding a solution using `serde_with`:

```rust
serde_with::with_prefix!(services "services_");

#[derive(Debug, Clone, Deserialize)]
pub struct Config {
    // ...
    #[serde(flatten, with = "services")]
    pub services: HashMap<String, String>,
}
```

Anything in the form of `SERVICES_X=y` will get written to the hashmap like `{"x": "y"}` which works well for situations where the names and number of services aren't known at compile time.

**Comment by softprops** [comment]
Nice one! I'm going to have to capture some of these in documentation form. I get asked about this from time to time. Thanks for reaching out.
