### ISSUE TITLE
Is envy unmaintained?

### ISSUE THREAD

**Issue by SkyfallWasTaken** [softprops/envy#76]
Just wanted to ask whether or not this crate is still being maintained or not.

If it isn't, that's fine - I'd simply like to know whether or not I should just fork the crate to fix the problems that I have. Please don't take this issue as pressure :)

**Comment by SkyfallWasTaken** [comment]
@softprops sorry for the ping, but are there any updates on this?

**Comment by jayvdb** [comment]
I recommend switching to https://github.com/Xuanwo/serde-env

**Comment by softprops** [comment]
Hi folks what features would you like to see? 

The reason there hasn’t been much activity is that the scope of this crate is intentionally narrow: converting end variables into struct types. That was essentially the first version

**Comment by SkyfallWasTaken** [comment]
@softprops I do agree that envy doesn't exactly need any more features - the main thing would probably be just fixing the lowercase renamed field bug, which seems to be one of the main complaints on issues

**Comment by softprops** [comment]
would  https://github.com/softprops/envy/pull/72 cover that?

**Comment by SkyfallWasTaken** [comment]
Yep, I think so, thanks!

**Comment by eliad-wiz** [comment]
@softprops do you plan releasing a new version (and publishing to crates.io)?
