### ISSUE TITLE
upgrade to serde 1.0

### ISSUE THREAD

**Issue by softprops** [softprops/envy#8]
https://github.com/serde-rs/serde/releases/tag/v1.0.0

**Comment by Boscop** [comment]
+1

**Comment by blanham** [comment]
Any updates on this? I started looking at it myself but I'd have to learn all of Serde's internals.

**Comment by softprops** [comment]
I've got a branch but its not passing the tests yet. I was planning on trying to get that out over the long weekend this weekend.

**Comment by softprops** [comment]
took a bit of work but I like the result and this gave me an opportunity to cache up on serde's newer interfaces. Anyway [0.3.0](https://crates.io/crates/envy) should be up on crate.io. now
